### ISSUE TITLE
Crash on Quest "Old Wounds"

### ISSUE THREAD

**Issue by admiralzeech** [Ashok0/EnderalVREssentials#2]
Hi, I'm getting an impassable crash on the quest "Old Wounds", in the orphanage.

When Tharael is leaning over the desk, explaining that he wants you to search for hidden safes, just after you reply, "I'll let you know if I find anything", the game will crash to desktop.

I'm using v1.0 of the modlist.

I've also disabled some mods and added some of my own, but mostly cosmetic stuff.

Do you get this crash?  How can I troubleshoot or bypass this?

Thanks!

**Comment by Ashok0** [comment]
Hi, I haven't gotten that far into the game yet.  If you can send me a saved game through MEGA or Google Drive, I would love to investigate the issue further.

You can optionally disable ALL mods except the "base" mods in MO2 and see if the "Old Wounds" issue clears up, it would help pinpoint if the problem is being caused by a specific mod.

**Comment by Ashok0** [comment]
Hi, I haven't gotten that far into the game yet.  If you can send me the saved game through MEGA or Google Drive, I would love to investigate the issue further.

**Comment by admiralzeech** [comment]
Thanks!  Here's the savegame.  I'll try disabling the mods as well when I have a moment in a few days.

Speaking of disabling mods, the mod that makes that guy a follower after the Quest causes the First Seer to be hostile to you.  I had to disable it to progress this questline.

**Comment by Ashok0** [comment]
Hi, I took a look at your saved game and got an instant crash too after replying to Tharael.  The crash to desktop is oddly caused by the "Kolapon's Undead Creatures Replacer" mod.  Deleting the plugin file 'Undead Creatures Replacer.esp' fixes the problem and you can proceed with the quest.  

I have removed this plugin starting with EVRE v1.05 and have updated the Tharael follower mod to v2.0 which should fix the problem with the First Seer being hostile.  And you can just update the follower mod manually if you don't want to update your modlist thru Wabbajack.  :)

**Comment by admiralzeech** [comment]
Thanks so much!
