### ISSUE TITLE
Quest "Our mark on this world"

### ISSUE THREAD

**Issue by admiralzeech** [Ashok0/EnderalVREssentials#6]
Hi, when I talk to the elf girl in Frostcliff Tavern, she invites me to play a game with her to discuss her quest.

However, when the game automatically starts, I just get a UI window to end it immediately, after which the elf girl cannot be spoken to anymore and the quest is stuck.

**Comment by Ashok0** [comment]
Hi, thank you for bringing this to my attention.   I would love to look into these issues at Frostcliff Tavern and the Riverville Dragon Aerie but haven't gotten that far into the game yet.  Do you have any saved games at these locations so I can quickly troubleshoot these problems?

**Comment by admiralzeech** [comment]
I was able to get the dragon back by disabling the Dragon replacer mod.  Is there a way for me to get the savegames to you without putting them up publically here?

**Comment by Ashok0** [comment]
You can e-mail me your saves directly to ashok0@gmail.com

**Comment by Ashok0** [comment]
Hi, I made it to Frostcliff Tavern and took a look at the issue with playing the game with Esme.  The problem seems to be caused by a bug with the Enderal VR v2.9 mod.  The minigame works fine if you temporarily downgrade Enderal VR to v2.4.1 using the old files from Nexus here:  https://www.nexusmods.com/enderalspecialedition/mods/8?tab=files  

Once you finish the minigame at the tavern, you can revert back to Enderal VR v2.9.  I'll report this issue in the official Discord channel.  Otherwise, this workaround seems to work fine so I'll consider this issue resolved for the time being.

**Comment by admiralzeech** [comment]
Ah, thanks.  Sorry I didn't send the save files, I haven't had a chance to play the game since I reported the issue.
